disabled_rules:
    - force_try
    - identifier_name
    - large_tuple

included:
    - Sources
    - ZiphyTests


# In order to deal with the huge number of violations, first set
# very high limits then iteratively reduce the limits and resolve
# the few violations. Repeat this until we find suitable limits.

line_length:
    warning: 250
    error: 250
