env:
  global:
  - secure: BAplQMTu0DvSIMTXfqaxgcg3uPODHGybQVvHYkbPRoBh9vyagYIAdAY1c9H8vr5DtgTzHv+z7uBZQcu17mWF2rJyX4v0a572HQccbNMVWaWCNWaXt+oRdhlej70OIg+tpimFWj142MYwg1j8w+L6lZI99rRzBiYFnffvN2VwoFAqJFqoyGDcwsNf1I6NDiNbrH+Kh2DlxSNooHwkjdSpfc7f9nJhKkxj9Fp9y26bKWICtiFYC2ZBORDoko2fW55BRrZPu+o8LN8uFlq3uBfqn0MzW5C5s4+63ZHhLw2DBMdesN5eDi0JPOBbD08Z5Ri+cYUOIzlyeNXOCbBhz2txAZ/FJaGv0/8Vtwnmihs66Nzpxx2ywfTNUv+D+P1ICaV/aoHAfYs13xnPMK2i7qxJhaFbFVso3COJgZ1/jHt0Cc3g+Rcbio4ruko6tdNw7Z4cHZnc7EgMd39mHtXxY0vry4tRn23Crj3HXswSNxvRNGjX0tvH/FzIRi1hHmCLHb88x8+qVyyIWslEGHBnJIdUiQdZXe1tkz2T8Z6D71VgAObLIB5eGpSV5D3wSJ6EH6vuM62c+j2YK20DFsBsdUvO5Wi9LvqWVEuALolNCIRSKhB6kgqBDNio7dT9RTZWjKuw2f+qmtKlXiy4DigfNDybJXuW2LjKoayyzhetyh029bs=
  - secure: btw04xsEAWtlSkSvH6u0+exIideCGY5LWnMuRD301j5GLr0eltb22e5bqeCCanVw/e8agVv32VgpJ4vrOFNreZrwKJEdExNnd9m7IkC24UYW+f8dMZHYVBmBQa93v4rlhlwLUqIEPk3W5cx/9STakXWFANSt4K7PMD78qn61Vd33XbKvAeKBYQp+RvGjPj1NmlTwgJxVnHYfmyN+53wQFNofNSFplMLKUW8EbLSX8dtF7HTyf9piQ8T1PQ8II/isb7N0SX7laJ89Xrw4sTZzxEim1w7z5QMnzTiVOP8AOKQ+Lm3ithXkkFq3D39wOT7m4jMzNiokB1Uc891KWZUIjCp7iRUeNsqubB/yIj9gHuMKjwS5bIJSijvI2I47IdMD4kMW6+3iRlmFqSQKR6TdOEv2WE5kbT5p232Zud0fRbJLXgskqq9cwQK4BpanJ3yvZ2fEq/DQvCr8Q1TnJw8p9GWue3CQ/ThutuzS0sNVA7H5o0laYrtrHf+GCy1CpI3V3FQA3yPoOiy8mKuWpEfXY00yggwWN8u9fcvwLslw73ZEUV1SnlsNn3p/HYu5OWBkEY9XNKxpyINPLaWt4uGPhpNqePliecMLORM9GINYfTWI9B1/XvB98jesd7KzbJJcEei4pq0jZ5vAGUe9UvQYMTIARxnX6NvwMshGKQb6MQQ=

language: ruby
cache: bundler
rvm: 2.4.0

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - develop
    - master

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - bundle exec danger
